### ISSUE TITLE
Object.keys vs Object.getOwnPropertyNames

### ISSUE THREAD

**Issue by jimthedev** [dai-shi/react-suspense-fetch#2]
Hey there. 

Lines 34: https://codesandbox.io/s/optimistic-nightingale-m617m

You can see object.keys shows as an empty array. Any ideas?

**Comment by dai-shi** [comment]
Confirmed the issue. Thanks.

I think it's because we pass `{}` to Proxy.
https://github.com/dai-shi/react-suspense-fetch/blob/6ec6369949896b31f9fec60ef71edc0ff6b5db75/src/index.ts#L136

I expected that Object.key is also trapped by `ownKeys` but maybe not.
Hm, not sure how to deal with it.

----
If this `{}` is the cause, this issue won't affect [reactive-react-redux](https://github.com/dai-shi/reactive-react-redux) nor [react-tracked](https://github.com/dai-shi/react-tracked), because they have the original object.

**Comment by dai-shi** [comment]
```js
> p = new Proxy({ a: 1 }, { ownKeys() { console.log('ownKeys'); return ['b']; } });
Proxy {a: 1}
> Object.keys(p)
ownKeys
[]
> Object.getOwnPropertyNames(p)
ownKeys
["b"]
```

OK, it's trapped, but returning `[]`. How come.
Hm, now wondering why it works in reactive-react-redux.

**Comment by dai-shi** [comment]
OK, Object.keys only lists `enumerable`s.
So, we need to trap getOwnPropertyDescriptor too.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/react-suspense-fetch/v/0.1.0

**Comment by dai-shi** [comment]
https://codesandbox.io/s/hungry-merkle-fnri1
It's fixed.

Thanks for reporting!

**Comment by jimthedev** [comment]
Thanks it is working great!
